services:
    bun-express:
        build:
            context: .
            dockerfile: ${DOCKERFILE}
            args:
                NODE_ENV: ${NODE_ENV}
        volumes:
            - .:/app
            - dist:/app/dist
        ports:
            - "${PORT}:${PORT}"
        environment:
            NODE_ENV: ${NODE_ENV}
            PORT: ${PORT}
            SUPABASE_URL: ${SUPABASE_URL}
            SUPABASE_KEY: ${SUPABASE_KEY}
            DATABASE_EXPORT_CSV: ${DATABASE_EXPORT_CSV}
            SUPABASE_BUCKET: ${SUPABASE_BUCKET}
        env_file:
            - .env.${ENV}

volumes:
    dist: null