services:
    bun-express:
        build:
            context: .
            dockerfile: ${DOCKERFILE}
            args:
                NODE_ENV: ${NODE_ENV}
        volumes:
            - .:/app
            - dist:/app/dist
        ports:
            - "${PORT}:${PORT}"
        environment:
            NODE_ENV: ${NODE_ENV}
        env_file:
            - .env.${ENV}

volumes:
    dist: null