services:
  python-serial-app:
    build: .
    container_name: raspberry-bridge-app
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"  # Map the serial port from host to container
    volumes:
      - .:/app  # Mount the current directory to /app in the container
    working_dir: /app
    command: python3 index.py  # Replace with the script you want to run
    environment:
      - PYTHONUNBUFFERED=1  # Ensure real-time logging/output
    restart: always  # Restart the container in case of failure
    ports:
      - "5000:5000"  # Example port mapping (optional, adjust as needed)
    network_mode: host  # Use host network mode (optional, adjust based on needs)