# Utilizza Debian 12 (Bookworm) come immagine base
FROM debian:bookworm

# Mantieni il container aggiornato e installa Python 3
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       python3 \
       python3-pip \
       python3-venv \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Imposta Python 3 come predefinito per il comando "python"
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1 \
    && update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1

# Crea una directory di lavoro nel container
WORKDIR /app

# Copia eventuali file necessari nella directory di lavoro
COPY . /app

ENV VIRTUAL_ENV=/opt/venv
RUN python -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN pip install --upgrade pip \
    && pip install -r requirements.txt

# Comando di avvio del container
CMD ["python", "-m", "src.index"]