services:
  bridge-slave:
    build:
      context: ./bridge_slave
      dockerfile: Dockerfile
    container_name: bridge-slave
    volumes:
      - ./bridge_slave:/app  # Monta il progetto bridge_slave
    environment:
      - PYTHONUNBUFFERED=1  # Abilita log in tempo reale
    restart: always
    command: python -m src.index

  bridge-master:
    build:
      context: ./bridge_master
      dockerfile: Dockerfile
    container_name: bridge-master
    volumes:
      - ./bridge_master:/app  # Monta il progetto bridge_master
    environment:
      - PYTHONUNBUFFERED=1  # Abilita log in tempo reale
    restart: always
    command: python -m src.index