services:
  bridge-slave:
    build:
      context: ./bridge_slave
      dockerfile: Dockerfile.prod
    container_name: bridge-slave
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"  # Map the serial port from host to container
    volumes:
      - ./bridge_slave:/app  # Monta il progetto bridge_slave
    environment:
      - PYTHONUNBUFFERED=1  # Abilita log in tempo reale
      - PYTHON_ENV=production
    restart: always

  bridge-master:
    build:
      context: ./bridge_master
      dockerfile: Dockerfile.prod
    container_name: bridge-master
    volumes:
      - ./bridge_master:/app  # Monta il progetto bridge_master
    environment:
      - PYTHONUNBUFFERED=1  # Abilita log in tempo reale
      - PYTHON_ENV=production
      - BROKER=${BROKER}
      - PORT=${PORT}
      - TOPIC=${TOPIC}
    restart: always